// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy29qTHPmvegNpMiHcCbSyhZqVYY4L5C8',
    appId: '1:119989632572:web:8fd25c7b828265da69cd39',
    messagingSenderId: '119989632572',
    projectId: 'nakupniseznam-6f38c',
    authDomain: 'nakupniseznam-6f38c.firebaseapp.com',
    storageBucket: 'nakupniseznam-6f38c.firebasestorage.app',
    measurementId: 'G-C9K22Q549D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSbtcvNQI7ZG3YK6xvb3h_ynZkSPXTOy8',
    appId: '1:119989632572:android:bae445c92bfc303069cd39',
    messagingSenderId: '119989632572',
    projectId: 'nakupniseznam-6f38c',
    storageBucket: 'nakupniseznam-6f38c.firebasestorage.app',
  );

}